#! /usr/bin/env python

from __future__ import print_function

import lhapdf
lhapdf.setVerbosity(0)

sets = []
for s in lhapdf.availablePDFSets():
    i = lhapdf.getPDFSet(s)
    sets.append([i.lhapdfID, i.name, i.dataversion])
for myid, name, version in sorted(sets):
    if myid > 0:
        print("%d %s %d" % (myid, name, version))
    else:
        import sys
        sys.stderr.write("Invalid set ID: %d %s %d\n" % (myid, name, version))
